from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton


menu_kb = ReplyKeyboardMarkup(resize_keyboard=True)
kb1 = KeyboardButton("🎮 Ігри")
kb2 = KeyboardButton("👣 Реферальна система")
kb3 = KeyboardButton("👤 Профіль")
kb4 = KeyboardButton("📚 Інформація")
kb_top22 = KeyboardButton('💎 Заробити')
kb_ch22 = KeyboardButton('➕ Завдання')
kb_top = KeyboardButton('🔥 Топ')
kb_ch = KeyboardButton('💬 Чат')
menu_kb.add(kb1, kb2)
menu_kb.add(kb3, kb4)
menu_kb.add(kb_top22, kb_ch22)
menu_kb.add(kb_top, kb_ch)

top_kb = ReplyKeyboardMarkup(resize_keyboard=True)
top1 = KeyboardButton('🔥 Дуель')
top2 = KeyboardButton('🔥 Партнер')
kb7 = KeyboardButton("⬅ Назад")
top_kb.add(top1)
top_kb.add(top2)
top_kb.add(kb7)

top_kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
top11 = KeyboardButton('🌌 Сьогодні')
top12 = KeyboardButton('🌠 Весь час')
kb772 = KeyboardButton("◀ Назад")
top_kb2.add(top11)
top_kb2.add(top12)
top_kb2.add(kb772)

profile_kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb5 = KeyboardButton("💸 Поповнити")
kb6 = KeyboardButton("💳 Вивести")
kbp699 = KeyboardButton("📤 Переказ Lucky")
kb7 = KeyboardButton("⬅ Назад")
profile_kb2.add(kb5, kb6)
profile_kb2.add(kbp699)
profile_kb2.add(kb7)

popov_kb221 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_221 = KeyboardButton("💳 UAH")
kb_2211 = KeyboardButton("💹 USDT")
kb7 = KeyboardButton("⬅ Назад")
popov_kb221.add(kb_221)
popov_kb221.add(kb_2211)
popov_kb221.add(kb7)

veref_kb = ReplyKeyboardMarkup(resize_keyboard=True)
veref1 = KeyboardButton('🛑 Верифікація', request_contact=True)
veref_kb.add(veref1)

start_kb = ReplyKeyboardMarkup(resize_keyboard=True)
start1 = KeyboardButton('/star')
start_kb.add(start1)

profile_kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
kbp5 = KeyboardButton("💸 Поповнити")
kbp6 = KeyboardButton("💳 Вивести")
kbp699 = KeyboardButton("📤 Переказ Lucky")
kbp6999 = KeyboardButton("🎁 Промо")
kbp7 = KeyboardButton("⬅ Назад")
profile_kb2.add(kbp5, kbp6)
profile_kb2.add(kbp699, kbp6999)
profile_kb2.add(kbp7)

games_kb = ReplyKeyboardMarkup(resize_keyboard=True)
kblotorea = KeyboardButton("🍓 Лоторея")
kb1528788 = KeyboardButton("Дуель 🎲")
kb15287882 = KeyboardButton("JET X 🚀")
kb15287 = KeyboardButton("LUCKY 🔮")
kb1528 = KeyboardButton("Однорукий бандит 🎰")
kb1529 = KeyboardButton("Баскетбол 🏀")
kb89 = KeyboardButton('Боулінг 🎳')
kb8 = KeyboardButton('Дартс 🎯')
kb9 = KeyboardButton("⬅ Назад")
games_kb.add(kblotorea)
games_kb.add(kb1528788)
games_kb.add(kb15287882)
games_kb.add(kb15287)
games_kb.add(kb1528)
games_kb.add(kb1529)
games_kb.add(kb89)
games_kb.add(kb8)
games_kb.add(kb9)

kb_graloto = ReplyKeyboardMarkup(resize_keyboard=True)

lotorea01 = KeyboardButton("💌 Купити - 10 UAH")
lotorea02 = KeyboardButton("⬅ Назад")
kb_graloto.add(lotorea01)
kb_graloto.add(lotorea02)



duel1kb = ReplyKeyboardMarkup(resize_keyboard=True)
duel1 = KeyboardButton('➕ Створити гру')
duel2 = KeyboardButton('⭕ Приєднатися')
duel3 = KeyboardButton("⬅ Назад")
duel1kb.add(duel1)
duel1kb.add(duel2)
duel1kb.add(duel3)

duel1kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
duel12 = KeyboardButton('🎲 Грати')
duel22 = KeyboardButton('♻ Рулетка')
duel32 = KeyboardButton("⬅ Назад")
duel1kb2.add(duel12)
duel1kb2.add(duel22)
duel1kb2.add(duel32)

info_kb = ReplyKeyboardMarkup(resize_keyboard=True)
infob = KeyboardButton("❔ Перевірені")
infob2 = KeyboardButton("❔ Реферальна система")
infob3 = KeyboardButton("❔ Поповнення/Вивід")
infob5 = KeyboardButton("⬅ Назад")
info_kb.add(infob)
info_kb.add(infob2)
info_kb.add(infob3)
info_kb.add(infob5)

stavka_kb = ReplyKeyboardMarkup(resize_keyboard=True)
kb15 = KeyboardButton('0 UAH 🔮')
kb10 = KeyboardButton('1 UAH 🔮')
kb11 = KeyboardButton('5 UAH 🔮')
kb12 = KeyboardButton('10 UAH 🔮')
kb13 = KeyboardButton('25 UAH 🔮')
kb14 = KeyboardButton('50 UAH 🔮')

kb16 = KeyboardButton("❌ Скасувати")
stavka_kb.add(kb15, kb10, kb11, kb12, kb13, kb14)
stavka_kb.add(kb16)

stavka_kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb102 = KeyboardButton('0 UAH 💰')
kb112 = KeyboardButton('1 UAH 💰')
kb122 = KeyboardButton('5 UAH 💰')
kb132 = KeyboardButton('10 UAH 💰')
kb142 = KeyboardButton('25 UAH 💰')
kb152 = KeyboardButton('50 UAH 💰')
kb14233 = KeyboardButton('100 UAH 💰')
kb15233 = KeyboardButton('200 UAH 💰')
kb162 = KeyboardButton("⬅ Назад")
stavka_kb2.add(kb102, kb112, kb122, kb132, kb142, kb152, kb14233, kb15233)
stavka_kb2.add(kb162)

stavkajet_kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb102j = KeyboardButton('0 UAH 🚀')
kb112j = KeyboardButton('1 UAH 🚀')
kb122j = KeyboardButton('5 UAH 🚀')
kb132j = KeyboardButton('10 UAH 🚀')
kb142j = KeyboardButton('25 UAH 🚀')
kb152j = KeyboardButton('50 UAH 🚀')
kb162j = KeyboardButton("⬅ Назад")
stavkajet_kb2.add(kb102j, kb112j, kb122j, kb132j, kb142j, kb152j)
stavkajet_kb2.add(kb162j)

stavka_kbduel = ReplyKeyboardMarkup(resize_keyboard=True)
kb102d = KeyboardButton('0 UAH 🎲')
kb112d = KeyboardButton('1 UAH 🎲')
kb122d = KeyboardButton('5 UAH 🎲')
kb132d = KeyboardButton('10 UAH 🎲')
kb142d = KeyboardButton('25 UAH 🎲')
kb152d = KeyboardButton('50 UAH 🎲')
kb14233d = KeyboardButton('100 UAH 🎲')
kb15233d = KeyboardButton('200 UAH 🎲')
kb162d = KeyboardButton('❌ Скасувати')
stavka_kbduel.add(kb102d, kb112d, kb122d, kb132d, kb142d, kb152d, kb14233d, kb15233d)
stavka_kbduel.add(kb162d)

back_kb = ReplyKeyboardMarkup(resize_keyboard=True)
bkb00 = KeyboardButton("⬅ Назад")
back_kb.add(bkb00)

back_kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
bkb01 = KeyboardButton("❌ Вийти")
back_kb2.add(bkb01)


back_kb133 = ReplyKeyboardMarkup(resize_keyboard=True)
bkb0133 = KeyboardButton("💰 Забрати")
back_kb133.add(bkb0133)

stavka_kb3 = ReplyKeyboardMarkup(resize_keyboard=True)
kb103 = KeyboardButton('0 UAH 🏀')
kb113 = KeyboardButton('1 UAH 🏀')
kb123 = KeyboardButton('5 UAH 🏀')
kb133 = KeyboardButton('10 UAH 🏀')
kb143 = KeyboardButton('25 UAH 🏀')
kb153 = KeyboardButton('50 UAH 🏀')
kb163 = KeyboardButton("⬅ Назад")
stavka_kb3.add(kb103, kb113, kb123, kb133, kb143, kb153)
stavka_kb3.add(kb163)


stavka_kb5 = ReplyKeyboardMarkup(resize_keyboard=True)
kb105 = KeyboardButton('0 UAH 🎯')
kb115 = KeyboardButton('1 UAH 🎯')
kb125 = KeyboardButton('5 UAH 🎯')
kb135 = KeyboardButton('10 UAH 🎯')
kb145 = KeyboardButton('25 UAH 🎯')
kb155 = KeyboardButton('50 UAH 🎯')
kb165 = KeyboardButton("⬅ Назад")
stavka_kb5.add(kb105, kb115, kb125, kb135, kb145, kb155)
stavka_kb5.add(kb165)

stavka_kb6 = ReplyKeyboardMarkup(resize_keyboard=True)
kb106 = KeyboardButton('0 UAH 🎳')
kb116 = KeyboardButton('1 UAH 🎳')
kb126 = KeyboardButton('5 UAH 🎳')
kb136 = KeyboardButton('10 UAH 🎳')
kb146 = KeyboardButton('25 UAH 🎳')
kb156 = KeyboardButton('50 UAH 🎳')
kb166 = KeyboardButton("⬅ Назад")
stavka_kb6.add(kb106, kb116, kb126, kb136, kb146, kb156)
stavka_kb6.add(kb166)

orel_reshka_kb = ReplyKeyboardMarkup(resize_keyboard=True)
kb17 = KeyboardButton("🟢")
kb18 = KeyboardButton("🔵")
kb18r = KeyboardButton("🔴")
orel_reshka_kb.add(kb17, kb18, kb18r)


popov_kb = ReplyKeyboardMarkup(resize_keyboard=True)
kb20 = KeyboardButton('''10 UAH 💸''')
kb21 = KeyboardButton('25 UAH 💸')
kb24 = KeyboardButton('50 UAH 💸')
kb25 = KeyboardButton('100 UAH 💸')
kb2477 = KeyboardButton('250 UAH 💸')
kb2578 = KeyboardButton('500 UAH 💸')
kb26 = KeyboardButton("⬅ Назад")
popov_kb.add(kb20, kb21)
popov_kb.add(kb24, kb25)
popov_kb.add(kb2477, kb2578)
popov_kb.add(kb26)

ikb = InlineKeyboardMarkup(row_width=1)
ik1 = InlineKeyboardButton(text="📋 Правила та політика конфідеційності.", url=f"https://telegra.ph/Kazino-Lucky-Star---pravila-ta-pol%D1%96tika-konf%D1%96denc%D1%96jnost%D1%96-09-24")
ikb.insert(ik1)

ikbper = InlineKeyboardMarkup(row_width=1)
ik1per = InlineKeyboardButton(text="📋 Правила та угода", url=f"https://telegra.ph/Pravila-ta-ugoda-na-sp%D1%96vpracyu-Perev%D1%96ren%D1%96-11-02")
ikbper.insert(ik1per)


kb_usdt = InlineKeyboardMarkup(row_width=1)
ikusdt1 = InlineKeyboardButton(text="💰 Поповнити", url=f"https://t.me/CryptoBot?start=IV0fPXiZbNr2")
kb_usdt.insert(ikusdt1)

ikb48 = InlineKeyboardMarkup(row_width=1)
ik148 = InlineKeyboardButton(text="Долучіться до чату гравців!", url=f"https://t.me/lucky_star_chat")
ikb48.insert(ik148)

ichat = InlineKeyboardMarkup(row_width=1)
ik00 = InlineKeyboardButton(text="Чат Lucky Star", url=f"https://t.me/lucky_star_chat")
ichat.insert(ik00)



c_kb = ReplyKeyboardMarkup(resize_keyboard=True)
c1 = KeyboardButton("❌ Скасувати")
c_kb.add(c1)


# ADMINS KEYBOARD

menu_admins = ReplyKeyboardMarkup(resize_keyboard=True)
kb101 = KeyboardButton("🎮 Ігри")
kb102 = KeyboardButton("👣 Реферальна система")
kb103 = KeyboardButton("👤 Профіль")
kb104 = KeyboardButton("📚 Інформація")
kb_top222 = KeyboardButton('💎 Заробити')
kb_ch222 = KeyboardButton('➕ Завдання')
kb105 = KeyboardButton("Адміністрація")
kb_top = KeyboardButton('🔥 Топ')
kb105ch = KeyboardButton('💬 Чат')
menu_admins.add(kb101, kb102)
menu_admins.add(kb_top222, kb_ch222)
menu_admins.add(kb103, kb104)
menu_admins.add(kb105)
menu_admins.add(kb_top, kb105ch)

#ADMIN 2 LEVEL
menu_admins2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb1012 = KeyboardButton("🎮 Ігри")
kb1022 = KeyboardButton("👣 Реферальна система")
kb1032 = KeyboardButton("👤 Профіль")
kb1042 = KeyboardButton("📚 Інформація")
kb_top2222 = KeyboardButton('💎 Заробити')
kb_ch2222 = KeyboardButton('➕ Завдання')
kb1052 = KeyboardButton("Адміністрація 2 LEVEL")
kb_top2 = KeyboardButton('🔥 Топ')
kb105ch2 = KeyboardButton('💬 Чат')
menu_admins2.add(kb1012, kb1022)
menu_admins2.add(kb_top2222, kb_ch2222)
menu_admins2.add(kb1032, kb1042)
menu_admins2.add(kb1052)
menu_admins2.add(kb_top2, kb105ch2)

admin_panel2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb1068882 = KeyboardButton("➕ Зарахування")
kb1072 = KeyboardButton("📁 База")
kb1154682 = KeyboardButton("♦ Інфоюзер")
kb11077892 = KeyboardButton("➕🎁 PROMOCODES")
kbstatis2 = KeyboardButton("📊 Статистика")
kb1082 = KeyboardButton("⬅ Назад")
admin_panel2.add(kb1068882)
admin_panel2.add(kb1072)
admin_panel2.add(kb1154682)
admin_panel2.add(kb11077892)
admin_panel2.add(kbstatis2)
admin_panel2.add(kb1082)

admin_panel = ReplyKeyboardMarkup(resize_keyboard=True)
kb106 = KeyboardButton("➕ Баланс")
kb106888 = KeyboardButton("➕ Зарахування")
kb107 = KeyboardButton("📁 База")
kb109 = KeyboardButton("🗯 Розсилка")
kb110 = KeyboardButton("🎁 Роздати Бонус")
kb115468 = KeyboardButton("♦ Інфоюзер")
kb1107789 = KeyboardButton("➕🎁 PROMOCODES")
kbstatis = KeyboardButton("📊 Статистика")
kb108 = KeyboardButton("⬅ Назад")
admin_panel.add(kb106)
admin_panel.add(kb106888)
admin_panel.add(kb107)
admin_panel.add(kb109)
admin_panel.add(kb110)
admin_panel.add(kb115468)
admin_panel.add(kb1107789)
admin_panel.add(kbstatis)
admin_panel.add(kb108)

pmtypes_kb = ReplyKeyboardMarkup(resize_keyboard=True)
pmtypes1 = KeyboardButton("Одноразовий")
pmtypes2 = KeyboardButton("Вічний")
kb11886465 = KeyboardButton("⬅ Назад")
pmtypes_kb.add(pmtypes1)
pmtypes_kb.add(pmtypes2)
pmtypes_kb.add(kb11886465)


bonus_kb = ReplyKeyboardMarkup(resize_keyboard=True)
kb112 = KeyboardButton('5 UAH 🎁')
kb114 = KeyboardButton('10 UAH 🎁')
kb115 = KeyboardButton('25 UAH 🎁')
kb116 = KeyboardButton('50 UAH 🎁')
kb118 = KeyboardButton("⬅ Назад")
bonus_kb.add(kb112, kb114)
bonus_kb.add(kb115, kb116)
bonus_kb.add(kb118)